Repository ProVal-Tech/ninjarmm, pull requests merged in 2025-07, with the labels that each got.

#5 NinjaOne Templates
  compound-conditions/_template.toml
  conditions/_template.toml
  custom-fields/_template.toml
  cw-manage-ticket-templates/_template.toml
  groups/_template.toml
  tasks/_template.toml
Labels: documentation

#4 Excessive Logon Attempts
  excessive-logon-attempts.ps1
Labels: documentation, enhancement

#6 Created Document
  scripts/duo-deployment-windows.ps1
Labels: bug, documentation
